config/routes.rb
Rails.application.routes.draw do
  root 'home#main'
  get '/index' => 'home#index'
  get '/recipients' => 'home#recipients'
  get '/peers' => 'home#peers'
  get '/additional_peers' => 'home#additional_peers'
  get '/terms' => 'home#terms'
  get '/privacy' => 'home#privacy'
  get '/data' => 'home#data'
  get '/about' => 'home#about'
  get 'help' => 'home#help'
  get '/careers' => 'home#careers'
  get '/filter_feedbacks' => 'home#filter_feedbacks'
  get '/impersonal_feedback_ids' => 'home#impersonal_feedback_ids'

  devise_for :users

  resources :organizations do
    member do
      post :add_user
    end
    collection do
      get :get_users
      put :update_user
      put :update_managers
      put :update_user_role
    end
  end

  resources :users do
    collection do
      post :registration_request
    end
  end

  resources :feedbacks do
    member do
      post :vote
      post :share
      post :destroy_notifications
      get :peers_in_agreement
      get :peers
    end
    collection do
      post :merge
    end
  end

  resources :comments do
    member do
      post :vote
    end
  end

  namespace :slack do
    resources :feedbacks
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  STATIC_SCALES = {
      small: "100x100#",
      large: "350x350>"
  }

  has_attached_file :avatar, default_url: ":style/missing.png",
                    styles: { small: "100x100#", large: "350x350>" },
                    processors: [:cropper]
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  belongs_to :organization
  has_many :feedbacks
  has_many :feedback_links
  has_many :comments
  has_many :comment_links
  has_many :manager_employees, foreign_key: 'employee_id'
  has_many :managers, through: :manager_employees
  has_many :notifications
  has_many :share_logs
  has_many :mail_logs
  has_many :mailer_settings

  validates_presence_of :email
  before_save :make_proper, :generate_user_tag, :update_user_tag
  after_create :set_mailer_settings, :email_credentials

  def full_name
    first_name + ' ' + last_name
  end

  def home_feedbacks(resonance=nil, search=nil)
    query = Feedback.joins(:feedback_links).where("feedbacks.author_id = ? or feedback_links.user_id = ? or feedbacks.user_id = ?", self.id, self.id, self.id).order('feedbacks.updated_at DESC').group('feedbacks.id')
    apply_filter(query, resonance, search)
  end

  def my_feedbacks(resonance=nil, search=nil)
    query = Feedback.where("feedbacks.user_id = ?", self.id).order("updated_at DESC").group('feedbacks.id')
    apply_filter(query, resonance, search)
  end

  def authored_feedbacks
    Feedback.where(author_id: self.id)
  end

  def peers
    User.where.not(id: self.id)
  end

  def can_vote?(feedback)
    ![feedback.author, feedback.user].include?(self)
  end

  def agrees_with(feedback_or_comment)
    if feedback_or_comment.instance_of?(Feedback)
      feedback_links.where(feedback: feedback_or_comment).first.try(:agree) || self == feedback_or_comment.author
    else
      comment_links.where(comment: feedback_or_comment).first.try(:agree) || self == feedback_or_comment.author
    end
  end

  def my_notifications
    notifications.joins(:feedback).where("feedbacks.user_id = ? or feedbacks.author_id = ?", self.id, self.id).select("DISTINCT feedbacks.id")
  end

  def home_notifications
    notifications.joins(feedback: :feedback_links).where("feedback_links.user_id = ?", self.id).select("DISTINCT feedbacks.id")
  end

  def fresh_feedbacks
    Feedback.joins(:notifications).where('notifications.user_id = ?', self.id)
  end

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def avatar_geometry(style = :original)
    @geometry ||= {}
    if avatar.path(style)
      @geometry[style] ||= Paperclip::Geometry.from_file(open(avatar.url(style)))
    else
      @geometry[style] = OpenStruct.new(width: 0, height: 0)
    end
  end

  def update_mailer_settings(params)
    if params
      mailer_settings.each do |setting|
        setting.update_attributes(active: !params[setting.name].nil?)
      end
    end
  end

  def following_up?(feedback)
    link = feedback_links.where(feedback: feedback).first
    if link
      feedback.followed_up? && !link.followed_up?
    end
  end

  def follow_up(feedback)
    link = feedback_links.where(feedback: feedback).first
    link.update_attributes(followed_up: true) if link
  end

private
  def reprocess_avatar
    avatar.reprocess!
  end

  def make_proper
    first_name.try(:capitalize!)
    last_name.try(:capitalize!)
  end

  def generate_user_tag
    unless self.id
      self.user_tag = '@' + self.first_name.to_s + self.last_name.to_s
      last_tag = User.where("user_tag LIKE '#{user_tag}%'").sort.last.try(:user_tag)
      if last_tag
        last_tag_suffix = last_tag.match(/-\d+/)
        next_tag = last_tag_suffix ? last_tag_suffix[0].match(/\d+/)[0].to_i + 1 : 1
        self.user_tag += "-#{next_tag.to_s}"
      end
    end
  end

  def update_user_tag
    if self.first_name_changed? || self.last_name_changed?
      suffix = self.user_tag.match(/-\d+/)
      suffix = suffix ? suffix[0] : ''
      self.user_tag = '@' + self.first_name.to_s + self.last_name.to_s + suffix
    end
  end

  def apply_filter(base_query, resonance=nil, search=nil)
    if resonance && resonance.count > 0
      values = resonance.map{ |r| Scoreable::RESONANCE_TEXT.index(r) }
      base_query = base_query.where(resonance_value: values)
    end
    if search
      terms = search.split(' ').map{|term| "content like '%#{term}%'"}
      terms = terms.join(' and ')
      base_query = base_query.where(terms)
    end
    base_query
  end

  def set_mailer_settings
    MailerSetting::DEFAULT_SETTINGS.each do |setting|
      self.mailer_settings.create(setting)
    end
  end

  def email_credentials
    self.save # completes the creation cycle, allowing Devise to create a
    self.send_reset_password_instructions
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(permitted_params)
    if @user.save
      redirect_to index_path
    else
      redirect_to root_path, error: @user.errors.full_messages
    end
  end

  def registration_request
    InternalMail.registration_request(params[:email]).deliver
    redirect_to root_path, notice: 'Thank you for your interest! We will contact you as soon as possible.'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if request.xhr?
      @user.update_attributes(bio: params[:value])
      render text: params[:value]
    else
      if permitted_params.keys.include?('password_confirmation') && !@user.valid_password?(params[:user][:current_password])
        flash[:error] = 'Invalid current password.'
        redirect_to edit_user_path and return
      end
      @user.assign_attributes(permitted_params)
      if @user.save
        @user.update_mailer_settings(params[:user]['mailer_settings'])
        @user.avatar.reprocess! if @user.cropping?
        sign_in @user, bypass: true
        flash[:notice] = "User successfully updated."
        redirect_to edit_user_path
      else
        flash[:error] = @user.errors.full_messages
        redirect_to edit_user_path
      end
    end
  end

private
  def permitted_params
    if params[:user][:password].blank?
      params.require(:user).permit(:email, :first_name, :last_name, :company, :avatar, :crop_x, :crop_y, :crop_w, :crop_h)
    else
      params.require(:user).permit(:email, :password, :password_confirmation, :reset_password_token, :first_name, :last_name, :company, :avatar, :crop_x, :crop_y, :crop_w, :crop_h)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def options_with_images(users)
    output = users.map do |user|
      "<option data-img-src='#{user.avatar.url{:large}}'>#{user.user_tag}</option>"
    end
    output.join('').html_safe
  end

end

app/views/users/_admin.html.haml
#admin
  .actions
    -#.button.cancel Bulk Import
    .button.confirm.add-user Add User
  %table#admin-grid
    %tbody

app/views/users/_general_settings.html.haml
.user-settings#general
  %h1 Account
  %h2 Change your basic account settings here

  .edit-user
    = form_for @user.becomes(User), url: { controller: 'users', action: 'update' }, html: { method: :put, multipart: true } do |f|
      %ul
        %li
          .label First Name
          = f.text_field :first_name, autofocus: true
        %li
          .label Last Name
          = f.text_field :last_name
        %li
          .label Email
          = f.email_field :email
        %li
          .label Profile Photo
          = f.file_field :avatar

        - for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] do
          %li
            = f.hidden_field attribute, id: attribute

        %li#avatar-handling
          .previewing
            %h4 Preview:
            #preview-container
              = image_tag @user.avatar.url(:large), :id => "current"
              = image_tag @user.avatar.url(:original), :id => "preview"
          .cropping
            %h4 Image:
            #cropbox
              = image_tag @user.avatar.url(:original)
        %li
          .submit-tag.active Save Changes

      %h1 Password Reset
      %h2 Change your password or recover your existing one
      = f.hidden_field :reset_password_token

      %ul
        %li
          .label
            = f.label :current_password
          = f.password_field :current_password
        %li
          .label New Password
          = f.password_field :password
        %li
          .label Verify Password
          = f.password_field :password_confirmation
        %li
          .label
          = link_to 'Forgot your password?', nil, tabindex: -1
        .submit-tag.active Save Changes

app/views/users/_manager_team.html.haml
- employees ||= current_user.employees
#manager-team
  %ul
    - employees.each do |employee|
      %li.employee{ id: employee.id }
        .avatar
          = image_tag employee.avatar.url(:large)
        .info
          .name= employee.full_name
          .title= employee.title

app/views/users/_notifications.html.haml
.user-settings#notifications
  %h1 Notifications
  %h2 Change your email notification settings

  .edit-user
    = form_for @user, url: { controller: 'users', action: 'update' }, html: { method: :put, multipart: true } do |f|
      %ul
        %li.label Send emails for:
        - @user.mailer_settings.each do |setting|
          %li
            = check_box_tag "user[mailer_settings][#{setting.name}]", 1, setting.active?
            .label= label_tag "user[mailer_settings][#{setting.name}]", setting.name.capitalize.gsub('_', ' ')

        %li
          .submit-tag.active Save Changes

app/views/users/_profile.html.haml
.profile
  .banner
  %table.data
    %tr
      %td
        .avatar
          = image_tag current_user.avatar.url(:large)
      %td
        .name= "#{current_user.first_name} #{current_user.last_name}"
        .title= current_user.title
  .status.editable{ 'data-action' => user_url(current_user) }
    = current_user.bio

  - if current_user.type == 'Manager'
    = render partial: 'users/manager_team'

app/views/users/edit.html.haml
:javascript
  var image_w, image_h, original_w, original_h, JcropAPI

  $(document).ready(function(){
      $('#cropbox').hover(function(){
          if (!$(this).find("img").attr("src").match(/missing\.png/)){
              initJcrop();
              JcropAPI = $("#cropbox").data('Jcrop');
          }
      })

      function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    if (input.files[0].size / 1024 < 8){
                        alert('Image file size must be greater than 8KB.')
                    } else if ( !$('input#user_avatar')[0].files[0].name.match(/^.*\.(jpg|JPG|gif|GIF|png|PNG|jpeg|JPEG)$/) ) {
                        alert('File must be an image file (jpg, png, gif).')
                    } else {
                        if (typeof JcropAPI !== 'undefined'){
                          JcropAPI.destroy();
                          $('.cropping').append("<div id='cropbox'><img src='" + e.target.result + "'></div>")
                        } else {
                          $('#cropbox').find('img').attr('src', e.target.result);
                        }
                        var img = $("#cropbox img")[0];
                        original_w = img.naturalWidth;
                        original_h = img.naturalHeight;
                        console.log(original_w);
                        console.log(original_h);
                        initJcrop();
                        $('#preview-container').find('img').attr('src', e.target.result);
                    }
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

        $('input#user_avatar').change(function(){
            readURL($(this)[0]);
        });

  });

  function initJcrop(){
        image_w = $('#cropbox').find('img').width();
        image_h = $('#cropbox').find('img').height();
        original_w = #{@user.avatar_geometry(:original).width}
        original_h = #{@user.avatar_geometry(:original).height}
        $('#cropbox').Jcrop({
            onChange: update_crop,
            onSelect: update_crop,
            aspectRatio: 1
        });
  }

  function update_crop(coords) {
      var rx = (image_w * 100) / (original_w * coords.w );
      var ry = (image_h * 100) / (original_h * coords.h );
      $('#current').hide();
      $('#preview').show();
      $('#preview').css({
          width: Math.round(rx * original_w) + 'px',
          height: Math.round(ry * original_h) + 'px',
          marginLeft: '-' + Math.round(coords.x * rx * original_w / image_w) + 'px',
          marginTop: '-' + Math.round(coords.y * ry * original_h / image_h) + 'px'
      });

      var ratio_w = original_w / image_w;
      var ratio_h = original_h / image_h;
      $("#crop_x").val(Math.round(coords.x * ratio_w));
      $("#crop_y").val(Math.round(coords.y * ratio_h));
      $("#crop_w").val(Math.round(coords.w * ratio_w));
      $("#crop_h").val(Math.round(coords.h * ratio_h));
  }

.devise
  %p.errors= flash[:error]
  %p.notices= flash[:notice]

.column#left

  %ul#settings-menu
    %li.selected.general
      General
      .chevron
    %li.notifications
      Notifications
      .chevron

  .copyright
    Copyright 2016 Prophet
    %ul.links
      %li= link_to 'About', about_path
      %li= link_to 'Help', help_path
      %li= link_to 'Terms', terms_path
      %li= link_to 'Privacy', privacy_path


.column#middle
  = render partial: 'general_settings'
  = render partial: 'notifications'

.column#right
  = render partial: 'users/profile'