config/routes.rb
Rails.application.routes.draw do
  root 'home#main'
  get '/index' => 'home#index'
  get '/recipients' => 'home#recipients'
  get '/peers' => 'home#peers'
  get '/additional_peers' => 'home#additional_peers'
  get '/terms' => 'home#terms'
  get '/privacy' => 'home#privacy'
  get '/data' => 'home#data'
  get '/about' => 'home#about'
  get 'help' => 'home#help'
  get '/careers' => 'home#careers'
  get '/filter_feedbacks' => 'home#filter_feedbacks'
  get '/impersonal_feedback_ids' => 'home#impersonal_feedback_ids'

  devise_for :users

  resources :organizations do
    member do
      post :add_user
    end
    collection do
      get :get_users
      put :update_user
      put :update_managers
      put :update_user_role
    end
  end

  resources :users do
    collection do
      post :registration_request
    end
  end

  resources :feedbacks do
    member do
      post :vote
      post :share
      post :destroy_notifications
      get :peers_in_agreement
      get :peers
    end
    collection do
      post :merge
    end
  end

  resources :comments do
    member do
      post :vote
    end
  end

  namespace :slack do
    resources :feedbacks
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :prevent_snooping, only: [:filter_feedbacks]

  def about; end
  def help; end
  def data; end
  def terms; end
  def privacy; end
  def careers; end

  def main
    redirect_to index_path if user_signed_in?
  end

  def index
    @feedbacks = current_user.home_feedbacks.paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def impersonal_feedback_ids
    if current_user
      render json: current_user.home_feedbacks.map(&:id) - current_user.my_feedbacks.map(&:id)
    else
      render nothing: true
    end
  end

  def recipients
    @recipients = autocomplete_attributes([current_user, current_user.peers].flatten)
    respond_to do |format|
      format.json { render json: @recipients.to_json }
    end
  end

  def peers
    @peers = autocomplete_attributes(current_user.peers)
    respond_to do |format|
      format.json { render json: @peers.to_json }
    end
  end

  def additional_peers
    @feedback = Feedback.find(params[:id])
    # TODO: optimize the following statement. Too many DB calls
    users = current_user.peers - @feedback.peers - [@feedback.author] - [@feedback.user]
    respond_to do |format|
      format.json { render json: autocomplete_attributes(users) }
    end
  end

  # TODO: prevent all of these from hitting the DB twice (FIRST check that the results aren't just cached)
  def filter_feedbacks
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      @feedbacks = @user.my_feedbacks(params[:resonance], params[:search])
      all_user_feedbacks = @user.my_feedbacks
    elsif params[:manager].present? && current_user.is_a?(Manager)
      @feedbacks = current_user.employee_feedbacks(params[:resonance], params[:search])
      all_user_feedbacks = current_user.employee_feedbacks
    else
      @feedbacks = current_user.home_feedbacks(params[:resonance], params[:search])
      all_user_feedbacks = current_user.home_feedbacks
    end
    @feedbacks = @feedbacks.paginate(page: params[:page])
    html = render_to_string(partial: 'feedbacks/index', locals: { feedbacks: @feedbacks })
    resonances = { resonant: all_user_feedbacks.resonant.count.count, mixed: all_user_feedbacks.mixed.count.count, isolated: all_user_feedbacks.isolated.count.count }
    if params[:page]
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.json { render json: { feedbacks: html, resonances: resonances } }
      end
    end
  end

private
  def prevent_snooping
    if params[:user_id].present? &&
        ((!current_user.is_a?(Manager) && params[:user_id].to_i != current_user.id) ||
            (current_user.is_a?(Manager) && !current_user.employees.map(&:id).push(current_user.id).include?(params[:user_id].to_i)))
      render nothing: true, status: :forbidden
    end
  end

end

app/views/home/_footer.html.haml
.footer
  %ul.business-links
    %li= link_to 'Terms and Conditions'
    %li= link_to 'Privacy Policy'
    %li= link_to 'Data Policy'
    %li= link_to 'Help'
    %li= link_to 'Careers'

app/views/home/_viewing_as.html.haml
.text
  = user.full_name.upcase
.delete
  x

app/views/home/about.html.haml
%div
  %h4
    About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us. About us.

  %h4
    About us. About us. About us. About us. About us. About us. About us.

app/views/home/careers.html.haml
%div
  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 
  
  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

  %h4
    This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. This is our careers page. 

app/views/home/data.html.haml
%div
  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 
  
  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

  %h4
    This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. This is your data policy. 

app/views/home/filter_feedbacks.js.erb
var pagination = $('.pagination');
pagination.eq(0).closest('#infinite-scrolling').remove();
$('#feedbacks').append('<%= j render partial: 'feedbacks/index', locals: { feedbacks: @feedbacks } %>');
<% if @feedbacks.next_page %>
    identifyFreshFeedbacks();
<% end %>

app/views/home/footer.html.haml
.footer
  %ul.business-links
    %li= link_to 'Terms and Conditions'
    %li= link_to 'Privacy Policy'
    %li= link_to 'Data Policy'
    %li= link_to 'Help'
    %li= link_to 'Careers'

app/views/home/help.html.haml
%div
  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 
  
  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

  %h4
    This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. This is our help page. 

app/views/home/index.html.haml
.column#left
  .feedback-summary.filters
    %h2 Filter by Resonance
    %ul
      %li
        .description.resonant Resonant
        .number-bubble#resonant
          %span= @feedbacks.resonant.count.count
      %li
        .description.mixed Mixed
        .number-bubble#mixed
          %span= @feedbacks.mixed.count.count
      %li
        .description.isolated Isolated
        .number-bubble#isolated
          %span= @feedbacks.isolated.count.count




.column#middle
  #filter-tags
    .resonance-tags

  = render partial: 'feedbacks/form'

  #feedbacks
    = render partial: 'feedbacks/index', locals: { feedbacks: @feedbacks }



.column#right
  = render partial: 'users/profile'


- if current_user.is_a?(Admin)
  = render partial: 'users/admin'

app/views/home/index.js.erb
var pagination = $('.pagination');
pagination.eq(0).closest('#infinite-scrolling').remove();
$('#feedbacks').append('<%= j render partial: 'feedbacks/index', locals: { feedbacks: @feedbacks } %>');
<% if @feedbacks.next_page %>
    identifyFreshFeedbacks();
<% end %>

app/views/home/main.html.haml
%div
  #home-left
    A better way to send and receive feedback at work.

  #home-right
    Sign Up
    #blurb
      Send us your information below so we can reach out to you and get Prophet set up at your company!

    = form_tag registration_request_users_path, id: 'registration' do
      .name-info
        = text_field_tag :first_name, '', placeholder: 'First Name'
        = text_field_tag :last_name, '', placeholder: 'Last Name'
      .additional-info
        = text_field_tag :email, '', placeholder: 'Email'
        = text_field_tag :email_confirmation, '', placeholder: 'Confirm Email'
        = text_field_tag :company, '', placeholder: 'Company'

      .legal
        By clicking Sign Up, you agree to our Terms and that you have read our Data Policy, including our cookie use.
      #sign_up
        .submit-tag{ 'tabindex' => 1 } Sign Up

app/views/home/privacy.html.haml
%div
  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 
  
  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 

  %h4
    This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. This is your privacy policy. 