config/routes.rb
Rails.application.routes.draw do
  root 'home#main'
  get '/index' => 'home#index'
  get '/recipients' => 'home#recipients'
  get '/peers' => 'home#peers'
  get '/additional_peers' => 'home#additional_peers'
  get '/terms' => 'home#terms'
  get '/privacy' => 'home#privacy'
  get '/data' => 'home#data'
  get '/about' => 'home#about'
  get 'help' => 'home#help'
  get '/careers' => 'home#careers'
  get '/filter_feedbacks' => 'home#filter_feedbacks'
  get '/impersonal_feedback_ids' => 'home#impersonal_feedback_ids'

  devise_for :users

  resources :organizations do
    member do
      post :add_user
    end
    collection do
      get :get_users
      put :update_user
      put :update_managers
      put :update_user_role
    end
  end

  resources :users do
    collection do
      post :registration_request
    end
  end

  resources :feedbacks do
    member do
      post :vote
      post :share
      post :destroy_notifications
      get :peers_in_agreement
      get :peers
    end
    collection do
      post :merge
    end
  end

  resources :comments do
    member do
      post :vote
    end
  end

  namespace :slack do
    resources :feedbacks
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/modals/_add_user.html.haml
.modal#add-user
  .header
    .text Add User
    .close x
    
  - organization = current_user.organization.id
  = form_for :user, url: add_user_organization_path(organization), remote: true do |f|
    %ul
      %li
        .label First Name
        = f.text_field :first_name
      %li
        .label Last Name
        = f.text_field :last_name
      %li
        .label Email
        = f.email_field :email
      %li
        .label Title
        = f.text_field :title
      %li
        .label Profile Photo
        = f.file_field :avatar
    = f.hidden_field :organization_id, value: organization

    .actions
      .submit-tag.active{ tabindex: 0 } Create
      .cancel{ tabindex: 0 } Cancel

app/views/modals/_delete_comment.html.haml
.modal#delete-comment
  .header
    .text Delete
    .close x
  .text
    Are you sure you want to delete your comment?

  .actions
    .submit-tag{ tabindex: 0 } Delete
    .cancel{ tabindex: 0 } Cancel

app/views/modals/_merge_confirmation.html.haml
- feedback_1 ||= nil
- feedback_2 ||= nil # merge target
.modal#merge-confirmation{ style: 'display:none' }
  .header
    .text Merge
    .close x
  .top
    %h2
      Feedback merging is IRREVERSIBLE! Merging these feedbacks will combine their peer lists and comment threads into a single,
      bigger thread. This is an organizational tool for combining feedbacks sent to you about the same thing.

  - [feedback_1, feedback_2].each_with_index do |feedback, index|
    .merge-feedback.feedback{ class: index == 1 ? 'merge-target' : '' }
      .banner
        .avatar
          = image_tag feedback.author.avatar.url(:large)
        .data
          .address= address_info(feedback, current_user)
          .stats= "#{pluralize(feedback.comments.count, 'comment')}, #{pluralize(feedback.peers.count, 'peer')}"
          .timestamp= "#{time_ago_in_words(feedback.created_at)} ago"
      .content
        = simple_format(feedback.content)
    - if index == 0
      .into INTO

  .actions
    .submit-tag{ tabindex: 0 } Merge
    .cancel{ tabindex: 0 } Cancel

app/views/modals/_share_list.html.haml
.modal#share-list
  .header
    .text Agree
    .close x
  %ul
    -#%li
    -#  .avatar
    -#    %img
    -#  .data
    -#    .name
    -#    .title

app/views/modals/_share_panel.html.haml
.modal#share-panel
  .header
    .text Share
    .close x
  .top
    .banner
      .avatar
        %img
      .data
        .address
        .timestamp
    .content

  .additional-peers
    = text_area_tag :additional_peers, '', placeholder: 'Tag additional peers here (@JohnDoe, @MarySue...)'

  .actions
    .share{ tabindex: 0 } Share
    .cancel{ tabindex: 0 } Cancel